"""empty message

Revision ID: 63e75d2a198b
Revises: 7a4a335c28d0
Create Date: 2021-08-10 10:03:03.355574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e75d2a198b'
down_revision = '7a4a335c28d0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
